import { ThemeContextProvider } from "../../../context/ContextProvider";
import Wrapper from "./Wrapper";
import "./globals.css";
import { CssBaseline } from "@mui/material";

export const metadata = {
  title: "KIU-QEC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CssBaseline />
      <body>
        <ThemeContextProvider>
          <Wrapper>{children}</Wrapper>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
